# Discord bot token
token = ""

# Bot prefix and status
prefix = ""
status = ""

# The ids of all users who will have acces to owner commands
owner_ids = [
    XXXXXXXXXXXXXXXXXX,
    XXXXXXXXXXXXXXXXXX,
    XXXXXXXXXXXXXXXXXX,
]

# The ids for your discord server and channel
guild_id = XXXXXXXXXXXXXXXXXX
error_channel = XXXXXXXXXXXXXXXXXX
dnkl_channel = XXXXXXXXXXXXXXXXXX
ticket_channel = XXXXXXXXXXXXXXXXXX
log_channel = XXXXXXXXXXXXXXXXXX
registration_channel = XXXXXXXXXXXXXXXXXX
partner_channel = XXXXXXXXXXXXXXXXXX

# The name of your Hypixel guild
guild_handle = ""

# Gexp requirements for the guild
new_member_req = XXXX
member_req = XXXX
resident_req = XXXX
active_req = XXXX
dnkl_req = XXXX


# Names of allied guilds
allies = [
    "",
    "",
    "",
    "",
    ""
]

# A list of Hypixel API keys for making requests
api_keys = [
"",
"",
"",
"",
"",
"",
]

# The names of discord ticket categories
[ticket_categories]
generic = ""
registration = ""
other = ""
reports = ""
milestones = ""
dnkl = ""