# Discord bot token
token = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

# Bot prefix and status
prefix = ""
status = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

# The ids of all users who will have acces to owner commands
owner_ids = [
    12345,
    12345,
]

# The ids for your discord server and channel (Note: dnkl stands for do-not-kick-list)
guild_id = XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
error_channel = XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
dnkl_channel = XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
ticket_channel = XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
log_channel = XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
registration_channel = XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
staff_announcements_channel = XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
partner_channel = XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
qotd_channel = XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
qotd_ans_channel = XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
milestones_channel = XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
milestones_category = XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX



# The name of your Hypixel guild
guild_handle = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

# Gexp requirements for the guild
new_member_req = 0
member_req = 0
resident_req = 0
active_req = 0
dnkl_req = 0

# The requirements for joining the GvG team
gvg_bw_fkdr = 0
gvg_bw_wins = 0
gvg_sw_kdr = 0
gvg_sw_wins = 0
gvg_duels_kills = 0
gvg_duels_wlr = 0

# Names of allied guilds
allies = [
    "",
    "",
    "",
    "",
    "",
    "",
]

# A list of Hypixel API keys for making requests
api_keys = [
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
]

# The names of discord ticket categories
[ticket_categories]
generic = "ABC"
other = "DEF"
report = "GHI"
milestone = "JKL"
dnkl = "DNKL"
